apiVersion: apps/v1
kind: Deployment
metadata:
  name: conductor-redis
spec:
  selector:
    matchLabels:
      app: conductor-redis
  template:
    metadata:
      labels:
        app: conductor-redis
    spec:
      containers:
        - name: conductor-redis
          image: {{ .Values.redis.image }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: {{ .Values.redis.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: conductor-redis
spec:
  selector:
    app: conductor-redis
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
