defaultReplicaCount: 1
conductor:
  type: NodePort
  swagger_ui:
    port: 8080
  conductor_ui:
    port: 5000
  replicaCount: 1
  image:
    repository: conductoross/conductor-standalone
    pullPolicy: IfNotPresent
    tag: "3.15.0"
postgres:
  port: 5432
  exposed_port: 6432
  image: postgres
  env:
    POSTGRES_USER: "conductor"
    POSTGRES_PASSWORD: "conductor"
redis:
  port: 6379
  image: redis:6.2.3-alpine
  